AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for S3 Images Thumbnailer stack.

Parameters:
  CloudFrontPriceClass:
    Type: String
    Description: The CloudFront distribution price class
    Default: 'PriceClass_200'
    AllowedValues:
      - 'PriceClass_100'
      - 'PriceClass_200'
      - 'PriceClass_All'

Globals:
  Api:
    BinaryMediaTypes:
      - image~1jpg
      - image~1png
  Function:
    Runtime: python3.7
    MemorySize: 512
    Timeout: 10
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  ThumbnailerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: thumbnailer/
      Handler: app.lambda_handler
      Policies:
        - AWSXrayWriteOnlyAccess
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:Get*
              Resource:
                - '*'
      Events:
        InfoAPI:
          Type: Api
          Properties:
            Path: /thumbnailer/info/{uri}
            Method: get
        ThumbmnailAPI:
          Type: Api
          Properties:
            Path: /thumbnailer/thumbnail/{uri}/long-edge/{long_edge_pixels}
            Method: get
        FitAPI:
          Type: Api
          Properties:
            Path: /thumbnailer/fit/{uri}/width/{width_pixels}/height/{height_pixels}
            Method: get

  CloudFrontOriginBucket:
    Type: AWS::S3::Bucket

  CloudFrontOriginBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudFrontOriginBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref CloudFrontOriginBucket, "/*" ] ]
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'CloudFront OAI for Thumbnailer'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - ThumbnailerFunction
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref CloudFrontOriginBucket
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName:
              !Join [ "", [ !Ref CloudFrontOriginBucket, ".s3.amazonaws.com" ] ]
            Id: !Ref CloudFrontOriginBucket
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [ "", [ "origin-access-identity/cloudfront/", !Ref CloudFrontOriginAccessIdentity ] ]
        PriceClass: !Ref CloudFrontPriceClass

Outputs:
  ThumbnailerApi:
    Description: "API Gateway endpoint URL for Prod stage for Thumbnailer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/thumbnailer"
  CdnApi:
    Description: "Thumbnailer API URL"
    Value: !Join [ "", [ !GetAtt CloudFrontDistribution.DomainName, "/thumbnailer"  ] ]
