AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Thumbnailer API stack.

Globals:
  Api:
    BinaryMediaTypes:
      - image~1jpg
      - image~1png
  Function:
    Runtime: python3.7
    MemorySize: 512
    Timeout: 10
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  ThumbnailerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: thumbnailer/
      Handler: app.lambda_handler
      Policies:
        - AWSXrayWriteOnlyAccess
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:Get*
              Resource:
                - '*'
      Events:
        InfoAPI:
          Type: Api
          Properties:
            Path: /thumbnailer/info/{uri}
            Method: get
        ThumbmnailAPI:
          Type: Api
          Properties:
            Path: /thumbnailer/thumbnail/{uri}/long-edge/{long_edge_pixels}
            Method: get
        FitAPI:
          Type: Api
          Properties:
            Path: /thumbnailer/fit/{uri}/width/{width_pixels}/height/{height_pixels}
            Method: get

Outputs:
  ThumbnailerApi:
    Description: "API Gateway endpoint URL for Prod stage for Thumbnailer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/thumbnailer"
